### ISSUE TITLE
刷新的时候数据越界

### ISSUE THREAD

**Issue by RenYanLin** [PingerOne/SwipeRefreshDemo#2]
当我下拉刷新的时候，不等下拉刷新完成，再次下拉刷新会报数组越界
dispatchTouchEvent 主要是这个方法报的错

**Comment by RenYanLin** [comment]
大神有什么办法解决吗

**Comment by PingerOne** [comment]
你给个boolean值，下拉的时候为true，如果在下拉就把下拉屏蔽掉

**Comment by RenYanLin** [comment]
ower
